# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.13.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.13.2/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/sierra/Desktop/Impression_bot_3.5_MAC

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/sierra/Desktop/Impression_bot_3.5_MAC

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.13.2/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.13.2/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/sierra/Desktop/Impression_bot_3.5_MAC/CMakeFiles /Users/sierra/Desktop/Impression_bot_3.5_MAC/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/sierra/Desktop/Impression_bot_3.5_MAC/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named impression-bot

# Build rule for target.
impression-bot: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 impression-bot
.PHONY : impression-bot

# fast build rule for target.
impression-bot/fast:
	$(MAKE) -f CMakeFiles/impression-bot.dir/build.make CMakeFiles/impression-bot.dir/build
.PHONY : impression-bot/fast

ImpressionVisualBot.o: ImpressionVisualBot.cpp.o

.PHONY : ImpressionVisualBot.o

# target to build an object file
ImpressionVisualBot.cpp.o:
	$(MAKE) -f CMakeFiles/impression-bot.dir/build.make CMakeFiles/impression-bot.dir/ImpressionVisualBot.cpp.o
.PHONY : ImpressionVisualBot.cpp.o

ImpressionVisualBot.i: ImpressionVisualBot.cpp.i

.PHONY : ImpressionVisualBot.i

# target to preprocess a source file
ImpressionVisualBot.cpp.i:
	$(MAKE) -f CMakeFiles/impression-bot.dir/build.make CMakeFiles/impression-bot.dir/ImpressionVisualBot.cpp.i
.PHONY : ImpressionVisualBot.cpp.i

ImpressionVisualBot.s: ImpressionVisualBot.cpp.s

.PHONY : ImpressionVisualBot.s

# target to generate assembly for a file
ImpressionVisualBot.cpp.s:
	$(MAKE) -f CMakeFiles/impression-bot.dir/build.make CMakeFiles/impression-bot.dir/ImpressionVisualBot.cpp.s
.PHONY : ImpressionVisualBot.cpp.s

ProductList.o: ProductList.cpp.o

.PHONY : ProductList.o

# target to build an object file
ProductList.cpp.o:
	$(MAKE) -f CMakeFiles/impression-bot.dir/build.make CMakeFiles/impression-bot.dir/ProductList.cpp.o
.PHONY : ProductList.cpp.o

ProductList.i: ProductList.cpp.i

.PHONY : ProductList.i

# target to preprocess a source file
ProductList.cpp.i:
	$(MAKE) -f CMakeFiles/impression-bot.dir/build.make CMakeFiles/impression-bot.dir/ProductList.cpp.i
.PHONY : ProductList.cpp.i

ProductList.s: ProductList.cpp.s

.PHONY : ProductList.s

# target to generate assembly for a file
ProductList.cpp.s:
	$(MAKE) -f CMakeFiles/impression-bot.dir/build.make CMakeFiles/impression-bot.dir/ProductList.cpp.s
.PHONY : ProductList.cpp.s

custom_coordinates.o: custom_coordinates.cpp.o

.PHONY : custom_coordinates.o

# target to build an object file
custom_coordinates.cpp.o:
	$(MAKE) -f CMakeFiles/impression-bot.dir/build.make CMakeFiles/impression-bot.dir/custom_coordinates.cpp.o
.PHONY : custom_coordinates.cpp.o

custom_coordinates.i: custom_coordinates.cpp.i

.PHONY : custom_coordinates.i

# target to preprocess a source file
custom_coordinates.cpp.i:
	$(MAKE) -f CMakeFiles/impression-bot.dir/build.make CMakeFiles/impression-bot.dir/custom_coordinates.cpp.i
.PHONY : custom_coordinates.cpp.i

custom_coordinates.s: custom_coordinates.cpp.s

.PHONY : custom_coordinates.s

# target to generate assembly for a file
custom_coordinates.cpp.s:
	$(MAKE) -f CMakeFiles/impression-bot.dir/build.make CMakeFiles/impression-bot.dir/custom_coordinates.cpp.s
.PHONY : custom_coordinates.cpp.s

down_size.o: down_size.cpp.o

.PHONY : down_size.o

# target to build an object file
down_size.cpp.o:
	$(MAKE) -f CMakeFiles/impression-bot.dir/build.make CMakeFiles/impression-bot.dir/down_size.cpp.o
.PHONY : down_size.cpp.o

down_size.i: down_size.cpp.i

.PHONY : down_size.i

# target to preprocess a source file
down_size.cpp.i:
	$(MAKE) -f CMakeFiles/impression-bot.dir/build.make CMakeFiles/impression-bot.dir/down_size.cpp.i
.PHONY : down_size.cpp.i

down_size.s: down_size.cpp.s

.PHONY : down_size.s

# target to generate assembly for a file
down_size.cpp.s:
	$(MAKE) -f CMakeFiles/impression-bot.dir/build.make CMakeFiles/impression-bot.dir/down_size.cpp.s
.PHONY : down_size.cpp.s

find_values_x.o: find_values_x.cpp.o

.PHONY : find_values_x.o

# target to build an object file
find_values_x.cpp.o:
	$(MAKE) -f CMakeFiles/impression-bot.dir/build.make CMakeFiles/impression-bot.dir/find_values_x.cpp.o
.PHONY : find_values_x.cpp.o

find_values_x.i: find_values_x.cpp.i

.PHONY : find_values_x.i

# target to preprocess a source file
find_values_x.cpp.i:
	$(MAKE) -f CMakeFiles/impression-bot.dir/build.make CMakeFiles/impression-bot.dir/find_values_x.cpp.i
.PHONY : find_values_x.cpp.i

find_values_x.s: find_values_x.cpp.s

.PHONY : find_values_x.s

# target to generate assembly for a file
find_values_x.cpp.s:
	$(MAKE) -f CMakeFiles/impression-bot.dir/build.make CMakeFiles/impression-bot.dir/find_values_x.cpp.s
.PHONY : find_values_x.cpp.s

find_values_y.o: find_values_y.cpp.o

.PHONY : find_values_y.o

# target to build an object file
find_values_y.cpp.o:
	$(MAKE) -f CMakeFiles/impression-bot.dir/build.make CMakeFiles/impression-bot.dir/find_values_y.cpp.o
.PHONY : find_values_y.cpp.o

find_values_y.i: find_values_y.cpp.i

.PHONY : find_values_y.i

# target to preprocess a source file
find_values_y.cpp.i:
	$(MAKE) -f CMakeFiles/impression-bot.dir/build.make CMakeFiles/impression-bot.dir/find_values_y.cpp.i
.PHONY : find_values_y.cpp.i

find_values_y.s: find_values_y.cpp.s

.PHONY : find_values_y.s

# target to generate assembly for a file
find_values_y.cpp.s:
	$(MAKE) -f CMakeFiles/impression-bot.dir/build.make CMakeFiles/impression-bot.dir/find_values_y.cpp.s
.PHONY : find_values_y.cpp.s

get_file_name.o: get_file_name.cpp.o

.PHONY : get_file_name.o

# target to build an object file
get_file_name.cpp.o:
	$(MAKE) -f CMakeFiles/impression-bot.dir/build.make CMakeFiles/impression-bot.dir/get_file_name.cpp.o
.PHONY : get_file_name.cpp.o

get_file_name.i: get_file_name.cpp.i

.PHONY : get_file_name.i

# target to preprocess a source file
get_file_name.cpp.i:
	$(MAKE) -f CMakeFiles/impression-bot.dir/build.make CMakeFiles/impression-bot.dir/get_file_name.cpp.i
.PHONY : get_file_name.cpp.i

get_file_name.s: get_file_name.cpp.s

.PHONY : get_file_name.s

# target to generate assembly for a file
get_file_name.cpp.s:
	$(MAKE) -f CMakeFiles/impression-bot.dir/build.make CMakeFiles/impression-bot.dir/get_file_name.cpp.s
.PHONY : get_file_name.cpp.s

image_place.o: image_place.cpp.o

.PHONY : image_place.o

# target to build an object file
image_place.cpp.o:
	$(MAKE) -f CMakeFiles/impression-bot.dir/build.make CMakeFiles/impression-bot.dir/image_place.cpp.o
.PHONY : image_place.cpp.o

image_place.i: image_place.cpp.i

.PHONY : image_place.i

# target to preprocess a source file
image_place.cpp.i:
	$(MAKE) -f CMakeFiles/impression-bot.dir/build.make CMakeFiles/impression-bot.dir/image_place.cpp.i
.PHONY : image_place.cpp.i

image_place.s: image_place.cpp.s

.PHONY : image_place.s

# target to generate assembly for a file
image_place.cpp.s:
	$(MAKE) -f CMakeFiles/impression-bot.dir/build.make CMakeFiles/impression-bot.dir/image_place.cpp.s
.PHONY : image_place.cpp.s

image_type.o: image_type.cpp.o

.PHONY : image_type.o

# target to build an object file
image_type.cpp.o:
	$(MAKE) -f CMakeFiles/impression-bot.dir/build.make CMakeFiles/impression-bot.dir/image_type.cpp.o
.PHONY : image_type.cpp.o

image_type.i: image_type.cpp.i

.PHONY : image_type.i

# target to preprocess a source file
image_type.cpp.i:
	$(MAKE) -f CMakeFiles/impression-bot.dir/build.make CMakeFiles/impression-bot.dir/image_type.cpp.i
.PHONY : image_type.cpp.i

image_type.s: image_type.cpp.s

.PHONY : image_type.s

# target to generate assembly for a file
image_type.cpp.s:
	$(MAKE) -f CMakeFiles/impression-bot.dir/build.make CMakeFiles/impression-bot.dir/image_type.cpp.s
.PHONY : image_type.cpp.s

place_interactive.o: place_interactive.cpp.o

.PHONY : place_interactive.o

# target to build an object file
place_interactive.cpp.o:
	$(MAKE) -f CMakeFiles/impression-bot.dir/build.make CMakeFiles/impression-bot.dir/place_interactive.cpp.o
.PHONY : place_interactive.cpp.o

place_interactive.i: place_interactive.cpp.i

.PHONY : place_interactive.i

# target to preprocess a source file
place_interactive.cpp.i:
	$(MAKE) -f CMakeFiles/impression-bot.dir/build.make CMakeFiles/impression-bot.dir/place_interactive.cpp.i
.PHONY : place_interactive.cpp.i

place_interactive.s: place_interactive.cpp.s

.PHONY : place_interactive.s

# target to generate assembly for a file
place_interactive.cpp.s:
	$(MAKE) -f CMakeFiles/impression-bot.dir/build.make CMakeFiles/impression-bot.dir/place_interactive.cpp.s
.PHONY : place_interactive.cpp.s

print_area_regex.o: print_area_regex.cpp.o

.PHONY : print_area_regex.o

# target to build an object file
print_area_regex.cpp.o:
	$(MAKE) -f CMakeFiles/impression-bot.dir/build.make CMakeFiles/impression-bot.dir/print_area_regex.cpp.o
.PHONY : print_area_regex.cpp.o

print_area_regex.i: print_area_regex.cpp.i

.PHONY : print_area_regex.i

# target to preprocess a source file
print_area_regex.cpp.i:
	$(MAKE) -f CMakeFiles/impression-bot.dir/build.make CMakeFiles/impression-bot.dir/print_area_regex.cpp.i
.PHONY : print_area_regex.cpp.i

print_area_regex.s: print_area_regex.cpp.s

.PHONY : print_area_regex.s

# target to generate assembly for a file
print_area_regex.cpp.s:
	$(MAKE) -f CMakeFiles/impression-bot.dir/build.make CMakeFiles/impression-bot.dir/print_area_regex.cpp.s
.PHONY : print_area_regex.cpp.s

print_area_regex_prod_height.o: print_area_regex_prod_height.cpp.o

.PHONY : print_area_regex_prod_height.o

# target to build an object file
print_area_regex_prod_height.cpp.o:
	$(MAKE) -f CMakeFiles/impression-bot.dir/build.make CMakeFiles/impression-bot.dir/print_area_regex_prod_height.cpp.o
.PHONY : print_area_regex_prod_height.cpp.o

print_area_regex_prod_height.i: print_area_regex_prod_height.cpp.i

.PHONY : print_area_regex_prod_height.i

# target to preprocess a source file
print_area_regex_prod_height.cpp.i:
	$(MAKE) -f CMakeFiles/impression-bot.dir/build.make CMakeFiles/impression-bot.dir/print_area_regex_prod_height.cpp.i
.PHONY : print_area_regex_prod_height.cpp.i

print_area_regex_prod_height.s: print_area_regex_prod_height.cpp.s

.PHONY : print_area_regex_prod_height.s

# target to generate assembly for a file
print_area_regex_prod_height.cpp.s:
	$(MAKE) -f CMakeFiles/impression-bot.dir/build.make CMakeFiles/impression-bot.dir/print_area_regex_prod_height.cpp.s
.PHONY : print_area_regex_prod_height.cpp.s

print_area_regex_prod_width.o: print_area_regex_prod_width.cpp.o

.PHONY : print_area_regex_prod_width.o

# target to build an object file
print_area_regex_prod_width.cpp.o:
	$(MAKE) -f CMakeFiles/impression-bot.dir/build.make CMakeFiles/impression-bot.dir/print_area_regex_prod_width.cpp.o
.PHONY : print_area_regex_prod_width.cpp.o

print_area_regex_prod_width.i: print_area_regex_prod_width.cpp.i

.PHONY : print_area_regex_prod_width.i

# target to preprocess a source file
print_area_regex_prod_width.cpp.i:
	$(MAKE) -f CMakeFiles/impression-bot.dir/build.make CMakeFiles/impression-bot.dir/print_area_regex_prod_width.cpp.i
.PHONY : print_area_regex_prod_width.cpp.i

print_area_regex_prod_width.s: print_area_regex_prod_width.cpp.s

.PHONY : print_area_regex_prod_width.s

# target to generate assembly for a file
print_area_regex_prod_width.cpp.s:
	$(MAKE) -f CMakeFiles/impression-bot.dir/build.make CMakeFiles/impression-bot.dir/print_area_regex_prod_width.cpp.s
.PHONY : print_area_regex_prod_width.cpp.s

product_data.o: product_data.cpp.o

.PHONY : product_data.o

# target to build an object file
product_data.cpp.o:
	$(MAKE) -f CMakeFiles/impression-bot.dir/build.make CMakeFiles/impression-bot.dir/product_data.cpp.o
.PHONY : product_data.cpp.o

product_data.i: product_data.cpp.i

.PHONY : product_data.i

# target to preprocess a source file
product_data.cpp.i:
	$(MAKE) -f CMakeFiles/impression-bot.dir/build.make CMakeFiles/impression-bot.dir/product_data.cpp.i
.PHONY : product_data.cpp.i

product_data.s: product_data.cpp.s

.PHONY : product_data.s

# target to generate assembly for a file
product_data.cpp.s:
	$(MAKE) -f CMakeFiles/impression-bot.dir/build.make CMakeFiles/impression-bot.dir/product_data.cpp.s
.PHONY : product_data.cpp.s

ratio_resize_logo.o: ratio_resize_logo.cpp.o

.PHONY : ratio_resize_logo.o

# target to build an object file
ratio_resize_logo.cpp.o:
	$(MAKE) -f CMakeFiles/impression-bot.dir/build.make CMakeFiles/impression-bot.dir/ratio_resize_logo.cpp.o
.PHONY : ratio_resize_logo.cpp.o

ratio_resize_logo.i: ratio_resize_logo.cpp.i

.PHONY : ratio_resize_logo.i

# target to preprocess a source file
ratio_resize_logo.cpp.i:
	$(MAKE) -f CMakeFiles/impression-bot.dir/build.make CMakeFiles/impression-bot.dir/ratio_resize_logo.cpp.i
.PHONY : ratio_resize_logo.cpp.i

ratio_resize_logo.s: ratio_resize_logo.cpp.s

.PHONY : ratio_resize_logo.s

# target to generate assembly for a file
ratio_resize_logo.cpp.s:
	$(MAKE) -f CMakeFiles/impression-bot.dir/build.make CMakeFiles/impression-bot.dir/ratio_resize_logo.cpp.s
.PHONY : ratio_resize_logo.cpp.s

ratio_resize_prod.o: ratio_resize_prod.cpp.o

.PHONY : ratio_resize_prod.o

# target to build an object file
ratio_resize_prod.cpp.o:
	$(MAKE) -f CMakeFiles/impression-bot.dir/build.make CMakeFiles/impression-bot.dir/ratio_resize_prod.cpp.o
.PHONY : ratio_resize_prod.cpp.o

ratio_resize_prod.i: ratio_resize_prod.cpp.i

.PHONY : ratio_resize_prod.i

# target to preprocess a source file
ratio_resize_prod.cpp.i:
	$(MAKE) -f CMakeFiles/impression-bot.dir/build.make CMakeFiles/impression-bot.dir/ratio_resize_prod.cpp.i
.PHONY : ratio_resize_prod.cpp.i

ratio_resize_prod.s: ratio_resize_prod.cpp.s

.PHONY : ratio_resize_prod.s

# target to generate assembly for a file
ratio_resize_prod.cpp.s:
	$(MAKE) -f CMakeFiles/impression-bot.dir/build.make CMakeFiles/impression-bot.dir/ratio_resize_prod.cpp.s
.PHONY : ratio_resize_prod.cpp.s

regexing.o: regexing.cpp.o

.PHONY : regexing.o

# target to build an object file
regexing.cpp.o:
	$(MAKE) -f CMakeFiles/impression-bot.dir/build.make CMakeFiles/impression-bot.dir/regexing.cpp.o
.PHONY : regexing.cpp.o

regexing.i: regexing.cpp.i

.PHONY : regexing.i

# target to preprocess a source file
regexing.cpp.i:
	$(MAKE) -f CMakeFiles/impression-bot.dir/build.make CMakeFiles/impression-bot.dir/regexing.cpp.i
.PHONY : regexing.cpp.i

regexing.s: regexing.cpp.s

.PHONY : regexing.s

# target to generate assembly for a file
regexing.cpp.s:
	$(MAKE) -f CMakeFiles/impression-bot.dir/build.make CMakeFiles/impression-bot.dir/regexing.cpp.s
.PHONY : regexing.cpp.s

turnToAlpha.o: turnToAlpha.cpp.o

.PHONY : turnToAlpha.o

# target to build an object file
turnToAlpha.cpp.o:
	$(MAKE) -f CMakeFiles/impression-bot.dir/build.make CMakeFiles/impression-bot.dir/turnToAlpha.cpp.o
.PHONY : turnToAlpha.cpp.o

turnToAlpha.i: turnToAlpha.cpp.i

.PHONY : turnToAlpha.i

# target to preprocess a source file
turnToAlpha.cpp.i:
	$(MAKE) -f CMakeFiles/impression-bot.dir/build.make CMakeFiles/impression-bot.dir/turnToAlpha.cpp.i
.PHONY : turnToAlpha.cpp.i

turnToAlpha.s: turnToAlpha.cpp.s

.PHONY : turnToAlpha.s

# target to generate assembly for a file
turnToAlpha.cpp.s:
	$(MAKE) -f CMakeFiles/impression-bot.dir/build.make CMakeFiles/impression-bot.dir/turnToAlpha.cpp.s
.PHONY : turnToAlpha.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... impression-bot"
	@echo "... ImpressionVisualBot.o"
	@echo "... ImpressionVisualBot.i"
	@echo "... ImpressionVisualBot.s"
	@echo "... ProductList.o"
	@echo "... ProductList.i"
	@echo "... ProductList.s"
	@echo "... custom_coordinates.o"
	@echo "... custom_coordinates.i"
	@echo "... custom_coordinates.s"
	@echo "... down_size.o"
	@echo "... down_size.i"
	@echo "... down_size.s"
	@echo "... find_values_x.o"
	@echo "... find_values_x.i"
	@echo "... find_values_x.s"
	@echo "... find_values_y.o"
	@echo "... find_values_y.i"
	@echo "... find_values_y.s"
	@echo "... get_file_name.o"
	@echo "... get_file_name.i"
	@echo "... get_file_name.s"
	@echo "... image_place.o"
	@echo "... image_place.i"
	@echo "... image_place.s"
	@echo "... image_type.o"
	@echo "... image_type.i"
	@echo "... image_type.s"
	@echo "... place_interactive.o"
	@echo "... place_interactive.i"
	@echo "... place_interactive.s"
	@echo "... print_area_regex.o"
	@echo "... print_area_regex.i"
	@echo "... print_area_regex.s"
	@echo "... print_area_regex_prod_height.o"
	@echo "... print_area_regex_prod_height.i"
	@echo "... print_area_regex_prod_height.s"
	@echo "... print_area_regex_prod_width.o"
	@echo "... print_area_regex_prod_width.i"
	@echo "... print_area_regex_prod_width.s"
	@echo "... product_data.o"
	@echo "... product_data.i"
	@echo "... product_data.s"
	@echo "... ratio_resize_logo.o"
	@echo "... ratio_resize_logo.i"
	@echo "... ratio_resize_logo.s"
	@echo "... ratio_resize_prod.o"
	@echo "... ratio_resize_prod.i"
	@echo "... ratio_resize_prod.s"
	@echo "... regexing.o"
	@echo "... regexing.i"
	@echo "... regexing.s"
	@echo "... turnToAlpha.o"
	@echo "... turnToAlpha.i"
	@echo "... turnToAlpha.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

